### ISSUE TITLE
Node Version

### ISSUE THREAD

**Issue by bnb** [costajob/app-servers#1]
Hello!

I like the idea behind this project - I've seen some people requesting this recently, as the last one I saw Node in was pre-io.js (but, admittedly, I haven't looked at performance reviews a lot).

However, Node v4 is, if you're using the _current_ version, LTS. It would be beneficial and fair to also run Node's v6 latest branch - that's what the majority of software is running, sans a smaller group of Enterprise solutions that need the extreme stability of the LTS version.

If you have any questions, I'd be happy to answer or try to pull in appropriate people to answer them!

**Comment by costajob** [comment]
Hi Bnb!
Thanks for suggesting, i will try with node V6 as you suggest and run benchmarks again.

**Comment by costajob** [comment]
Hi,

updated benchmarks with Node version 6.7.0: slightly better throughput recorded ;)

Best
