### ISSUE TITLE
Test accuracy could be improved

### ISSUE THREAD

**Issue by schainker** [costajob/app-servers#10]
Running the client threads and server threads on the same machine is costing you valuable time during context switches, especially for platforms like OTP.

In other words (as @evadne puts it):
1. The observer effect. 
2. NUMA. 
3. Context switching. 
4. Lack of core affinity.

... are all affecting your results, probably generating poor performance across **all** benchmarks, not just OTP!

**Comment by costajob** [comment]
That's a pretty obvious, by the way the cost of the drawbacks is equal for all of the platforms, so i can assume the results are not faked by this setup.
Also consider wrk is suited for this scenarios, it uses just one process with 5 threads, consuming a mere 2MB of RAM and stressing just one core.
Anyway if OTP is suffering here is a peculiarity of its architecture, others platforms react pretty fine.

**Comment by schainker** [comment]
Measuring how fast runtime can do something primarily IO bound doesn't really measure much in the context of what our apps are really built to do.  Why not make all the tests single threaded and see what happens?

**Comment by costajob** [comment]
It is

**Comment by costajob** [comment]
Indeed the "purpose" (aside for fun) to test these platforms is to see how different, minimal implementations behave under heavy loading. 
Why do limit pre-forking model platforms like Ruby, Python or Node to run one single process only? 
It is like spawning multiple process for Java, GO or Rust: pointless.
I also measure the complexity of the setup of each platform, to measure not only throughput, but also efficiency: in this regards languages like Ruby, Python, GO and Crystal (and Clojure to a lesser extent) are clear winners to me (i will add a paragraph about coding efficiency).

**Comment by costajob** [comment]
Anyway any experimentation is pretty welcome, feel free to fork and bench ;)
