### ISSUE TITLE
Clojure analysis

### ISSUE THREAD

**Issue by Xorlev** [costajob/app-servers#11]
> Concurrency and parallelism
>
> Clojure leverages on the JVM to deliver parallelism: indeed it parallelizes better than Java, since it uses all of the available cores.

I don't think you can say that at all, actually. It's using more of the CPU, but possibly for additional garbage collection or a property of the differing Jetty configurations. Ring Jetty is built on top of Jetty+Servlets. It's functionally equivalent but adds *more work* (e.g. allocations) on top of the raw Java/Jetty/Servlet3 test as far as this simple "Hello World" goes.

The configuration of Jetty is also differing between the two tests:

https://github.com/ring-clojure/ring/blob/master/ring-jetty-adapter/src/ring/adapter/jetty.clj#L132-L142

Ring Jetty has default configuration of Jetty, whereas your test with Jetty does not change Jetty's default configuration. For reference, Jetty's default configuration creates a new threadpool with max 200 threads (vs. 50). At the default thread stack size (1mb on most platforms), an additional 150 threads (that is, if the threadpool creates that many threads -- it creates as necessary) is an additional 150mb of memory which _can_ account for the extra memory (e.x. if Java/Jetty/Servlets is using 85 threads steady state and Clojure/Ring is using 50). In general you shouldn't really expect a stable or representative RSS from Java as it'll hold onto memory as it claims up to the max heap size. Run your benchmarks for longer and the footprint may well increase unless you cap the heap size.

Fundamentally, with the correct rigor you're just benchmarking the Ring library. But the analysis presented is incorrect.

**Comment by costajob** [comment]
Thanks for precise explanation, i'll do more research on this, since my JVM knowledge is very rusted... 
I am going to change the readme and try to follow your setting suggestions for Jetty.
The point i am stressing here is how simple is to create a HTTP layer with the different platforms, in that sense Clojure seem to be more friendly than Java for loc and setup.
Best

**Comment by costajob** [comment]
You are very true, Ring is creating 75 threads while Java+Jetty is creating 127. I'll try to edit Java configuration to use the same pool size. Also i dare to give JVM more warmup to test for performance boost.
Thanks

**Comment by costajob** [comment]
Done, i limited Java+Jetty max threads to 50 and get better throughput too.
I alse modified considerations based on your observations.
Thank you!
