### ISSUE TITLE
Test results qualification

### ISSUE THREAD

**Issue by romul** [costajob/app-servers#12]
Hi, thank you for detailed description of the benchmark. I've reproduced it step by step, but got different   ratio of results. As I understand, you have run tests on different days, so maybe you could rerun all of them all at once?
Besides, I noticed, that response length with considering of headers isn't the same. And some of servers didn't even calculate `date` header.

Here is my results:

| App Server                                        | Throughput (req/s) | Latency in ms (avg/stdev/max) | Response in bytes | 
| :------------------------------------------------ | -----------------: | ----------------------------: | ----------------: | 
| [Plug with Cowboy](#plug-with-cowboy)             |          43564.50  |             2.24/0.41/ 15.84  |              172  | 
| [Rack with Puma](#rack-with-puma)                 |          32947.19  |             0.39/0.11/ 17.38  |               72  |
| [Nim asynchttpserver](#nim-asynchttpserver)       |          60916.85  |             1.64/0.28/ 26.79  |               47  |
| [Node Cluster](#node-cluster)                     |          44437.09  |             2.27/0.92/ 58.59  |              139  | 
| [Ring with Jetty](#ring-with-jetty)               |          45946.47  |             2.39/3.81/129.38  |              159  |
| [Rust Hyper](#rust-hyper)                         |          55010.47  |             1.81/0.30/  4.90  |               84  |
| [Gunicorn with Meinheld](#gunicorn-with-meinheld) |          53362.82  |             1.87/0.30/  5.36  |              154  |
| [Servlet3 with Jetty](#servlet3-with-jetty)       |          50938.14  |             2.37/5.43/147.65  |              154  |
| [Colossus](#colossus)                             |          59850.19  |             1.67/0.28/  7.36  |               72  |
| [GO ServeMux](#go-servemux)                       |          49734.60  |             1.99/0.42/  9.39  |              123  |
| [Crystal HTTP](#crystal-http)                     |          67656.15  |             1.48/0.19/  4.56  |               95  |

**Comment by costajob** [comment]
Hi Romul, thanks for your testing. Just to know, on what platform did you benchmarked?
Indeed i see your numbers more or less confirm mines, but for Elixir.
For some reason my Mac is not fair with Elixir/Erlang i cannot squeeze the right numbers from BEAM (but you too are very close to Ruby).
I registered the numbers on different times, to copy with new version of the languages once they come out. Now and then i repeat the test for all of the languages, by registering the numbers only for highest throughput.
For the HTTP parsing: you're right, it seem some of the server just discard some headers, anyway the goal here is to see how standard (closer to) HTTP server libraries behave under heavy loading.
If you can suggest how to enlighten some of the headers from Java, GO and Erlang i'll be glad to add some more testing.
Best

**Comment by romul** [comment]
@costajob Yeah, but in my case Elixir/Erlang gives almost the same result as Node and Ring. Except Plug with Cowboy, all others have worse results comparing to your stand..
So, maybe you could try to reinstall Erlang and Elixir :-)
I recommend `[kerl](https://github.com/kerl/kerl) & [kiex](https://github.com/taylor/kiex)`

>  Just to know, on what platform did you benchmarked?
MacBook Pro 2013 (i7 - 2,3 GHz, 16 Gb 1600 MHz DDR3).

> If you can suggest how to enlighten some of the headers from Java, GO and Erlang i'll be glad to add some more testing.

Maybe I'll add `Date` header to these servers manually. I don't think that other headers affect results. But calculation of string representation of the current datetime very probably affects.

**Comment by costajob** [comment]
I am going to close this, since it's not a proper issue. Please do a fork and propose a pull: i will be glad to integrate your work.
Best
