### ISSUE TITLE
ASP.NET Core

### ISSUE THREAD

**Issue by kblok** [costajob/app-servers#17]
Would you accept a PR with a ASP.NET Core server?

**Comment by costajob** [comment]
Sure! I just wondering if i can run it on the OSX in order to provide records on the same platform. 
Is .NET platform OSX compatible yet?

**Comment by kblok** [comment]
@costajob yes, I'd would provide you the instructions but yes I'll code it on OSX.

**Comment by costajob** [comment]
That's fine, you're free to PR with the .NET solution, i'll be happy to integrate.
If you dare to add your observations on the summary paragraphs of README file they'll be very appreciated too ;)

**Comment by CShepartd** [comment]
Want ASP.NET Core too

**Comment by costajob** [comment]
Added to the bunch, courtesy of @kblok. 
Many thanks!
