### ISSUE TITLE
Add ponylang

### ISSUE THREAD

**Issue by 0joshuaolson1** [costajob/app-servers#19]
http://ponylang.org - they would be very interested if some toolstack can beat them.

**Comment by costajob** [comment]
Hi,

thanks for suggestion: i've just added Pony lang to the pack.

As you can see Pony throughput is not stellar, although memory consumption and CPUs are good.

I cannot figure out how setting "text/plain" header using the net/http example i've found on the official repository. If you know Pony and have any suggestions, they'll be very welcome ;)

Best

**Comment by 0joshuaolson1** [comment]
Cool. By the way, the code you use does reverse DNS. Do all of the benchmark implementations do this?

**Comment by costajob** [comment]
I fear they doesn't.
I just read the implementation on the official repo and tried to make it work.
If you dare to make some changes they are welcome ;)
Otherwise i will change it whenever i've more time delving into Pony.

**Comment by costajob** [comment]
Removed reverse DNS lookup (letting default value `None`): the throughput does not change at all.
Tomorrow i will record some more bench to confirm (i've not my workstation with me right now, just compared old code with new one on my MacBook Air).
I fear they are still tweaking with internal implementation of the language and are not focused on pure performance. Also the server implementation seem much more verbose than GO or Crystal, but even Nim is more straightforward to me.

**Comment by 0joshuaolson1** [comment]
That's fair. Thanks for making an effort.

**Comment by costajob** [comment]
Done: better memory consumption (but twice of Nim, Crystal and GO), CPUs less stressed and minimal throughput increase.
