### ISSUE TITLE
Bootstrap of plug

### ISSUE THREAD

**Issue by gaynetdinov** [costajob/app-servers#2]
Can you please clarify how did you run http server using elixir? 

```
I started elixir by using iex interactive console as described on Plug read-me.
```

Do I understand correctly that you did this?
```elixir
$ iex -S mix
iex> c "path/to/file.ex"
[MyPlug]
iex> {:ok, _} = Plug.Adapters.Cowboy.http MyPlug, []
{:ok, #PID<...>}
```

**Comment by costajob** [comment]
Yes, initial bootstrap was lkke that. Then i used a full app and started it via mix.
If you have any enhancements they are welcome.
