### ISSUE TITLE
Wrk on local host 

### ISSUE THREAD

**Issue by NobbZ** [costajob/app-servers#20]
To not have wrks load influence your servers you should not run it on the same system.

**Comment by costajob** [comment]
Indeed you are right. By the way `wrk` is very lightweight compared to, say, `httperf` or other "enterprise" tools.
Consider it just takes 130% CPU and just 3.5MB during the tests.
Anyway the `wrk` burden is constant across all tested platforms/languages, so i assume is pretty fair ;)

**Comment by costajob** [comment]
Moved wrk on a different server and adjusted benchmarks.
Thanks
