### ISSUE TITLE
Vibe.d running debug build + possible Bug in detection threadsPerCpu

### ISSUE THREAD

**Issue by Wulfklaue** [costajob/app-servers#26]
Finally some time at the PC. I took a quick look at your configuration and found it odd that the memory usage was so high for D. And after checking the command that you used to run, it downed on me that your running in debug mode.

Try:

```
dub build --build=release --compiler=ldc2 
```
The compiler switch may not be needed if you only have lcd installed. But if you have both installed, its possible it falls back to the slower ( but fast to compile DMD compiler and again in debug mode ). 

-----------

Next issue with the multithreading:

Try:
```
	auto settings = new HTTPServerSettings;
	settings.port = 9292;
	settings.bindAddresses = ["::1", "0.0.0.0"];

	settings.options |= HTTPServerOption.distribute;
	setupWorkerThreads(4);

	listenHTTP(settings, &hello);
	runApplication();
```

Try this code. I suspect that your worker threadcount is not being set to 4 but only to 1. I think there is a bug with the threadpercpu detection on your system because distribute really needs to use all 4 Cpu Cores and not one.

**Comment by costajob** [comment]
Thanks!
I cannot yet make Vibe run in parallel: i've got `segfault 11` by updating the code with the `setupWorkerThreads(4);`.
Anyway the `--build=release` flag made a huge difference on throughput!
Now Vibe performance is in the same league than NIM and others.

**Comment by costajob** [comment]
Please do a pull request if you've got a compiling version of Vibe running in parallel: i'll be happy to test it.

**Comment by Wulfklaue** [comment]
I was under the impression that Crystal there default compilation is already running optimizations. That is part of the reason why people complain that Crystals compilations are slow ( compared to other LLVM languages ). 

D is a strange creature because it has so many compilers.

DMD is the default and one with the latest release. It also the fasted for compiling reveling Go in compile speed but it is also slower in final speed.

That is why most people use DMD for development and then use LDC for release builds optimized for speed. Unfortunately, LDC always runs behind DMD in regards to release numbers. Used to be bad but now its only a few months difference.

GDC is now the dark horse because it was the ignored little brother until recently. One guy worked for years to rewrite the D code, to have D included into the official GCC. And GCC 8 will include official support for D. Impressive job by one guy. And that release is up to date to the latest version of D.

Complicated ;)

Now the speed you see if defiantly not the final speed. The problem is that while Crystal and D both use LLVM in this test, there are differences. D still has other memory safety tests active, that are not present in the Crystal version. You can disable those to level the playing level ( i need to look them up ). But those easily add another 10 to 20%. Unfortunately when people compare languages there are a lot of details that are easily missed in tests.

-----------

The Segfault is strange. I only tested the code yesterday with DMD, the default compiler under Windows. I will give LDC anther try tonight to see if i can replicate that error. Or if its a Osx specific bug.

If i can find i solution tonight, ill make a pull request. Take in account i am by no way a D expert ;)

**Comment by costajob** [comment]
Thanks for explanation, you make me curious about D: i will try it out, just to have a different point of view ;)

**Comment by costajob** [comment]
Anyway also in Crystal you have to specify `crystal build --release` to optimise code.
