### ISSUE TITLE
Alternative NodeJS HTTP Server

### ISSUE THREAD

**Issue by ohenepee** [costajob/app-servers#29]
I stumbled upon [this](https://github.com/mafintosh/turbo-http) which serves as a replacement for the standard library's `http` module. It claims high performance and efficiency.

Also, could you add a second benchmark for low-end specs (1 Core CPU + 512MB)... I guess that would speak a lot since most individuals/devs (except maybe startups) won't go in for full blown 16GB server until significant traffic is noticed.

**Comment by costajob** [comment]
Hi ohenepee,

i tried out `turbo-http`: unfortunately it doesn't wrap the pre-forking model granted by the `cluster` module and doesn't seem to support it either (it throws a 'address already in use' error on each process). 

Using a single process the throughput is, comprehensively, worst than standard server clustered:
```
Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.81ms  272.02us  12.41ms   91.28%
    Req/Sec    13.85k     0.89k   19.24k    92.10%
  1658307 requests in 30.10s, 117.03MB read
Requests/sec:  55092.16
Transfer/sec:      3.89MB
```

Also consider i tried to rely on standard libraries when possible. 

Regarding a minimal slice: i should rely on virtualization to limit server specs, but network does not behave nicely with the `wrk` tool.
Check memory consumption by the way: none of the servers consume the whole available 16GB of memory (consumed in part by the benchmarking tool), so you should have an approximation of what will happen on a less capable device.

Best

**Comment by ohenepee** [comment]
Thanks very much pal... I appreciate the fact that you actually tried.
