### ISSUE TITLE
Httpbeast is compiled without threads support

### ISSUE THREAD

**Issue by konradmb** [costajob/app-servers#31]
Nim's httpbeast is compiled without `--threads:on`. Using this flag would surely improve it's performance.

**Comment by costajob** [comment]
Hi, i've already done it, throughput is worse as it is memory consumption. 
It appears that, on Mac OS at least, Nim multi-threading is not able to use all of the CPUs: it hits 99% of usage.

```shell
./servers/httpbeast_server 
Starting 8 threads
Listening on port 9292
```

```shell
wrk -t 4 -c 100 -d30s --timeout 2000 http://0.0.0.0:9292
Running 30s test @ http://0.0.0.0:9292
  4 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.17ms  222.15us  14.33ms   90.17%
    Req/Sec    21.46k     1.94k   31.00k    89.86%
  2569344 requests in 30.10s, 323.44MB read
Requests/sec:  85359.04
Transfer/sec:     10.75MB
```

CPUs usage: 
<img width="560" alt="http_beast_cpus" src="https://user-images.githubusercontent.com/38143/48692269-b9a59c80-ebd5-11e8-9dc7-f7610b78a750.png">
