### ISSUE TITLE
ASP.NET Core built in Debug mode?

### ISSUE THREAD

**Issue by nlivaic** [costajob/app-servers#32]
Hi,

default for `dotnet run` is to build in `Debug`, as per https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-run?tabs=netcore21.

Would you consider doing a `dotnet run --configuration Release` and seeing if it gives better results?

Thank you.

**Comment by costajob** [comment]
I'll do and post the results, thanks!

**Comment by costajob** [comment]
Updated to .NET core 2.2 and started with Release option: no benefits on throughput unfortunately.
