### ISSUE TITLE
Multi-threaded httpbeast 

### ISSUE THREAD

**Issue by jackhftang** [costajob/app-servers#33]
Nim compiler by default do not turn on mutli-threaded support, but it doesn't mean nim or httpbeast is designed to be single-threaded. And it is very easy to turn on mutli-thread support by just adding one option `--threads:on`. 

```
nim c -d:release --threads:on servers/httpbeast_server.nim
```

Just like most of the lang/framework are concurrent, httpbeast should also be.

**Comment by costajob** [comment]
Hi, issue has already been highlighted here: https://github.com/costajob/app-servers/issues/31
