### ISSUE TITLE
I got 1285049 requests in 30.05s for Plug server

### ISSUE THREAD

**Issue by greentornado** [costajob/app-servers#9]
Running 30s test @ http://127.0.0.1:9292

   4 threads and 100 connections

   Thread Stats   Avg      Stdev     Max   +/- Stdev

    Latency     2.34ms    1.99ms  67.24ms   90.90%

    Req/Sec    10.75k     2.04k   17.82k    69.92%

   1285049 requests in 30.05s, 190.19MB read

  Requests/sec:  42761.97

  Transfer/sec:      6.33MB`

I think there is some wrong with the results of Plug
I'm running this test on a  2011 i7 mb pro

**Comment by costajob** [comment]
Hi,

what's strange with the Plug's results: i see you've got almost the same throughput of mine: 42761 req/sec VS 44105 req/sec.

By the way Elixir/Erlang are not suited for speed, but for managing millions of processes on a multi core platform, something not particularly stressed in this micro-benchmark, where i just stress the application server/HTTP implementation of each language.

Best
M.

**Comment by costajob** [comment]
After updating to Erlang 19.1 and Elixir 1..3.4 i've got a better throughput: ** 54823.15** req/sec
